### ISSUE TITLE
Private model, login option request

### ISSUE THREAD

**Issue by renoproc** [rebane2001/matterport-dl#67] opened 2022-07-22 13:55 UTC
Hi,
I would like to save a template that an agency sent me in my personal space my.matterport, 
matterport-dl is a great script, but as I have a free matterport account I can only share the model as a private share, which requires to be logged in.

Wouldn't there be a way to add to the script a way to log in to save templates in this setting ?
Thanks for your help.

```
Downloading base page...
Traceback (most recent call last):
  File "/Users/respinfo/Desktop/matterport-dl-brute-js/matterport-dl+brute-js.py", line 593, in <module>
    initiateDownload(pageId)
  File "/Users/respinfo/Desktop/matterport-dl-brute-js/matterport-dl+brute-js.py", line 467, in initiateDownload
    downloadPage(getPageId(url))
  File "/Users/respinfo/Desktop/matterport-dl-brute-js/matterport-dl+brute-js.py", line 387, in downloadPage
    raise Exception("Can't find urls")
Exception: Can't find urls
```

**Comment by rebane2001** [comment] 2022-07-22 14:16
Duplicate of #37

**Closed by rebane2001** 2022-07-22 14:16 UTC

**Comment by renoproc** [comment] 2022-07-22 14:35
good ! thanks for this quick reply :)
