### ISSUE TITLE
JS file unknown

### ISSUE THREAD

**Issue by mikhoul** [rebane2001/matterport-dl#47] opened 2022-03-02 18:32 UTC
![image](https://user-images.githubusercontent.com/5678673/156425581-6d883bdf-5d98-45db-8b6c-2ff86e2837ac.png)

If you need more information just ask me.

**Comment by dnlldl** [comment] 2022-03-03 04:00
duplicate of https://github.com/rebane2001/matterport-dl/issues/45 ...

**Comment by mitchcapper** [comment] 2024-08-04 06:52
This should be fixed now, please test again on master and let us know if not

**Closed by mitchcapper** 2024-08-04 06:52 UTC
