### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dev4lifes** [rebane2001/matterport-dl#136] opened 2024-09-24 06:48 UTC
### One or more sample matterport IDs / urls that reproduce the issue

roWLLMMmPL8

### Python version

3.12

### Steps to reproduce

PS D:\Work\MatterportTour\matterport-dl-main> python matterport-dl.py https://my.matterport.com/show/?m=roWLLMMmPL8 --base-folder my-tours --debug
Started up a download run Running python 3.12.6 on win32
Downloading capture of roWLLMMmPL8 with base page... https://my.matterport.com/show/?m=roWLLMMmPL8
Saved debug file: base_page.html
Downloading graph model data...
Doing advanced download of dollhouse/floorplan data...
Saved debug file: advanced_model_data_extracted.json
Saved debug file: advanced_model_data_from_GetModelDetails.json
Saved debug file: advanced_model_data_from_GetSnapshots.json
AdvancedDownload photos: 12 meshes: 2, locations: 71, tileset indexes: 0, textures: 2,
Going to download tileset 3d asset models
Downloading textures and previews for tileset 3d models
100%|█████████████████████████████████████████████████████████████████████████████| 1352/1352 [00:06<00:00, 201.11it/s]
Downloading static files...
100%|███████████████████████████████████████████████████████████████████████████████| 331/331 [00:03<00:00, 100.05it/s]
Downloading model info...
100%|█████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 579.50it/s]
Downloading plugins...
Downloading images...
100%|████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 3359.92it/s]
Downloading primary model assets...
100%|████████████████████████████████████████████████████████████████████████████| 36210/36210 [15:36<00:00, 38.65it/s]
Done, Total fetches: 37964 Skipped: 16 (0%) actual Request: 37948 (100%) Success: 9210 (24%) Failed403: 27438 (72%) Failed404: 22 (0%) FailedUnknown: 1278 (3%)!

### What went wrong

Done, Total fetches: 37964 Skipped: 16 (0%) actual Request: 37948 (100%) Success: 9210 (24%) Failed403: 27438 (72%) Failed404: 22 (0%) FailedUnknown: 1278 (3%)!

**Comment by mitchcapper** [comment] 2024-09-24 07:09
Sorry but what went wrong is missing?  Did it not work? Did you get an error?  If you are worried about the success rate it might not matter although it seems a bit high we do brute some things.

**Comment by dev4lifes** [comment] 2024-09-24 07:44
> Sorry but what went wrong is missing? Did it not work? Did you get an error? If you are worried about the success rate it might not matter although it seems a bit high we do brute some things.
Steps to Reproduce:
Execute the following command to download the Matterport tour:

python matterport-dl.py https://my.matterport.com/show/?m=roWLLMMmPL8 --base-folder my-tours --debug
The download process begins with the following messages:

Downloading the base page of the tour.
Downloading graph model data and advanced assets like dollhouse/floorplan data.
Downloading static files, model information, plugins, images, and primary model assets.
The download completes with the following statistics:

Total fetches: 37,964
Successful requests: 9,210 (24%)
Failed requests (403 Forbidden): 27,438 (72%)
Failed requests (404 Not Found): 22 (0%)
Unknown failures: 1,278 (3%)
What Went Wrong:
403 Forbidden Errors (72%): The majority of requests were denied access by the Matterport server, likely due to:

Missing permissions to access specific tour resources (e.g., images, 3D models, data files).
The tour might require additional authentication or special permissions.
404 Not Found Errors (0%): A small number of requests did not find the resources, possibly due to:

Files being removed or no longer existing on the server.
Incorrect paths to the requested files.
Unknown Failures (3%): These errors were not clearly identified, possibly due to:

The matterport-dl script not handling certain scenarios properly or unexpected server responses.
The tour does not display, likely due to the significant number of failed requests, especially the 403 Forbidden errors. Further investigation is needed to address these issues.

**Comment by mitchcapper** [comment] 2024-09-24 18:01
When you run the server to view it, if you can send the server.log after the 404 errors etc that it hits when trying to view will tell us what resources were missing.    Thanks.

**Comment by mitchcapper** [comment] 2024-09-24 18:04
trying it now myself will report if still need more info.

**Comment by mitchcapper** [comment] 2024-09-24 18:57
Yours:
`Done, Total fetches: 37964 Skipped: 16 (0%) actual Request: 37948 (100%) Success: 9210 (24%) Failed403: 27438 (72%) Failed404: 22 (0%) FailedUnknown: 1278 (3%)!`
My run:
`Done, Total fetches: 37964 Skipped: 16 (0%) actual Request: 37948 (100%) Success: 9210 (24%) Failed403: 27434 (72%) Failed404: 22 (0%) FailedUnknown: 1282 (3%)!`

Mine loads just fine.  Please provide server.log after running the server and trying to load in browser.

**Comment by dev4lifes** [comment] 2024-09-25 03:53
> Yours: `Done, Total fetches: 37964 Skipped: 16 (0%) actual Request: 37948 (100%) Success: 9210 (24%) Failed403: 27438 (72%) Failed404: 22 (0%) FailedUnknown: 1278 (3%)!` My run: `Done, Total fetches: 37964 Skipped: 16 (0%) actual Request: 37948 (100%) Success: 9210 (24%) Failed403: 27434 (72%) Failed404: 22 (0%) FailedUnknown: 1282 (3%)!`
> 
> Mine loads just fine. Please provide server.log after running the server and trying to load in browser.

thanks, It's working on localhost, but not working on hosting. Can you guide about upload tour on hosting?

**Comment by mitchcapper** [comment] 2024-09-25 04:51
If you are talking static hosting closing as dupe of #41

**Closed by mitchcapper** 2024-09-25 04:51 UTC
